In [34]:
import pandas as pd
import os
import numpy

In [5]:
files = os.listdir('json_files/')
files

['aquarius.csv',
 'aquarius.json',
 'aries.csv',
 'aries.json',
 'cancer.csv',
 'cancer.json',
 'capricorn.csv',
 'capricorn.json',
 'gemini.csv',
 'gemini.json',
 'leo.csv',
 'leo.json',
 'libra.csv',
 'libra.json',
 'pisces.csv',
 'pisces.json',
 'sagittarius.csv',
 'sagittarius.json',
 'scorpio.csv',
 'scorpio.json',
 'taurus.csv',
 'taurus.json',
 'tweet_cleaning.py',
 'virgo.csv',
 'virgo.json',
 'zodiac.csv',
 'zodiac.json']

In [8]:
files = [file for file in  files if file[-4:] == '.csv']
files

['aquarius.csv',
 'aries.csv',
 'cancer.csv',
 'capricorn.csv',
 'gemini.csv',
 'leo.csv',
 'libra.csv',
 'pisces.csv',
 'sagittarius.csv',
 'scorpio.csv',
 'taurus.csv',
 'virgo.csv',
 'zodiac.csv']

In [10]:
df = pd.read_csv('json_files/'+files[0])
df

,Unnamed: 0,text,user,retweets,favorites,datetime
0,0,RT @Kainin: Aquarius (Let the Sunshine in) htt...,TerraBranford28,1,0,Sat Nov 07 21:10:57 +0000 2020
1,1,RT @thewaterbxtch: üå´Ô∏è Air Signs üå´Ô∏è \nüå∏ Gemini ...,FathOmDivinity,3,0,Sat Nov 07 21:10:51 +0000 2020
2,2,RT @starheal: I think they forgot I‚Äôm an Aquar...,_yonaaB,28,0,Sat Nov 07 21:10:51 +0000 2020
3,3,RT @milkstrology: invitation: dress casual!! w...,BreonaAndrea,12,0,Sat Nov 07 21:10:43 +0000 2020
4,4,RT @milkstrology: *when someone is genuinely n...,Fave_UXDesigner,844,0,Sat Nov 07 21:10:43 +0000 2020
...,...,...,...,...,...,...
95,95,what‚Äôs the worst zodiac sign and why is it aqu...,yumekorion,0,2,Sat Nov 07 21:06:06 +0000 2020
96,96,@sandyreniguntla @aquarius_soul15 @SSMBc_u_l_t...,show_dude,0,0,Sat Nov 07 21:05:54 +0000 2020
97,97,RT @starheal: I think they forgot I‚Äôm an Aquar...,audkleinpell,28,0,Sat Nov 07 21:05:46 +0000 2020
98,98,"RT @zodiacashomes: Pisces,Aquarius &amp;Virgo ...",xtenabena,788,0,Sat Nov 07 21:05:40 +0000 2020
99,99,invitation: dress casual!! wear something comf...,milkstrology,12,133,Sat Nov 07 21:05:40 +0000 2020

In [14]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer 
analyzer = SentimentIntensityAnalyzer()
def get_score(s):
    if type(s) == str:
        return analyzer.polarity_scores(s)['compound']
    else:
        return 0.0

count    100.000000
mean       0.108008
std        0.530824
min       -0.851900
25%       -0.188825
50%        0.000000
75%        0.458800
max        0.913600
Name: score, dtype: float64

In [43]:
def get_weight(retweets):
    return numpy.log(retweets+1+numpy.e)

In [44]:
path = 'json_files'
summary = []
dfs = []
for file in files:

    df = pd.read_csv(os.path.join(path, file))

    df['score'] = df['text'].map(get_score)
    dfs.append(df)

    df['weights'] = df['retweets'].map(get_weight)
    df['weighted_score'] = df['score']*df['weights']

    df["weighted_score"].describe()


    score = df.weighted_score.describe()
    score.rename(file[:-4],inplace=True)
    summary.append(score)
    score.to_csv(os.path.join(path, "score_for_"+file))
    
summary

[count    100.000000
 mean       0.349854
 std        1.881590
 min       -4.381791
 25%       -0.330350
 50%        0.000000
 75%        1.247935
 max        5.017401
 Name: aquarius, dtype: float64,
 count    100.000000
 mean      -0.064103
 std        0.946661
 min       -4.053949
 25%       -0.012286
 50%        0.000000
 75%        0.000000
 max        2.144309
 Name: aries, dtype: float64,
 count    100.000000
 mean      -0.651824
 std        1.163949
 min       -5.233560
 25%       -0.833133
 50%       -0.833133
 75%        0.000000
 max        2.747383
 Name: cancer, dtype: float64,
 count    100.000000
 mean       1.099097
 std        2.081911
 min       -2.713659
 25%        0.000000
 50%        0.000000
 75%        2.498173
 max        4.778870
 Name: capricorn, dtype: float64,
 count    100.000000
 mean       0.622123
 std        1.826073
 min       -2.881411
 25%       -0.003513
 50%        0.000000
 75%        0.958189
 max        4.971078
 Name: gemini, dtype: float64,
 count    100.000000
 mean       0.194444
 std        1.008418
 min       -3.217282
 25%        0.000000
 50%        0.000000
 75%        0.000000
 max        5.364760
 Name: leo, dtype: float64,
 count    100.000000
 mean      -0.025011
 std        1.432796
 min       -3.288515
 25%       -0.280045
 50%        0.000000
 75%        0.161156
 max        4.998384
 Name: libra, dtype: float64,
 count    100.000000
 mean       0.196069
 std        2.104147
 min       -3.295165
 25%       -0.670551
 50%        0.000000
 75%        1.302250
 max        4.667364
 Name: pisces, dtype: float64,
 count    100.000000
 mean       1.084189
 std        1.997217
 min       -2.771941
 25%        0.000000
 50%        0.425365
 75%        2.040791
 max       10.204202
 Name: sagittarius, dtype: float64,
 count    100.000000
 mean       1.507369
 std        2.231261
 min       -2.853152
 25%        0.000000
 50%        0.501075
 75%        2.803655
 max        5.130027
 Name: scorpio, dtype: float64,
 count    100.000000
 mean       0.124200
 std        2.181325
 min       -3.279559
 25%       -0.841871
 50%        0.000000
 75%        0.900514
 max        5.476754
 Name: taurus, dtype: float64,
 count    100.000000
 mean       0.419337
 std        1.360263
 min       -3.323164
 25%        0.000000
 50%        0.000000
 75%        1.071917
 max        6.384461
 Name: virgo, dtype: float64,
 count    100.000000
 mean       0.166548
 std        1.235362
 min       -4.037970
 25%       -0.033718
 50%        0.000000
 75%        0.721900
 max        4.027055
 Name: zodiac, dtype: float64]

In [32]:
dfs[0]

,Unnamed: 0,text,user,retweets,favorites,datetime,score
0,0,RT @Kainin: Aquarius (Let the Sunshine in) htt...,TerraBranford28,1,0,Sat Nov 07 21:10:57 +0000 2020,0.4939
1,1,RT @thewaterbxtch: üå´Ô∏è Air Signs üå´Ô∏è \nüå∏ Gemini ...,FathOmDivinity,3,0,Sat Nov 07 21:10:51 +0000 2020,0.8316
2,2,RT @starheal: I think they forgot I‚Äôm an Aquar...,_yonaaB,28,0,Sat Nov 07 21:10:51 +0000 2020,0.0000
3,3,RT @milkstrology: invitation: dress casual!! w...,BreonaAndrea,12,0,Sat Nov 07 21:10:43 +0000 2020,0.4530
4,4,RT @milkstrology: *when someone is genuinely n...,Fave_UXDesigner,844,0,Sat Nov 07 21:10:43 +0000 2020,0.4215
...,...,...,...,...,...,...,...
95,95,what‚Äôs the worst zodiac sign and why is it aqu...,yumekorion,0,2,Sat Nov 07 21:06:06 +0000 2020,-0.6249
96,96,@sandyreniguntla @aquarius_soul15 @SSMBc_u_l_t...,show_dude,0,0,Sat Nov 07 21:05:54 +0000 2020,-0.6249
97,97,RT @starheal: I think they forgot I‚Äôm an Aquar...,audkleinpell,28,0,Sat Nov 07 21:05:46 +0000 2020,0.0000
98,98,"RT @zodiacashomes: Pisces,Aquarius &amp;Virgo ...",xtenabena,788,0,Sat Nov 07 21:05:40 +0000 2020,0.2500
99,99,invitation: dress casual!! wear something comf...,milkstrology,12,133,Sat Nov 07 21:05:40 +0000 2020,0.4530

In [49]:

def get_weight(retweets):
    return numpy.log(retweets+1+numpy.e)
df['weights'] = df['retweets'].map(get_weight)
df['weighted_score'] = df['score']*df['weights']

df["weighted_score"].describe()

count    100.000000
mean       0.166548
std        1.235362
min       -4.037970
25%       -0.033718
50%        0.000000
75%        0.721900
max        4.027055
Name: weighted_score, dtype: float64

In [53]:
df_summary = pd.DataFrame(summary)
df_summary

,count,mean,std,min,25%,50%,75%,max
aquarius,100.0,0.349854,1.881590,-4.381791,-0.330350,0.000000,1.247935,5.017401
aries,100.0,-0.064103,0.946661,-4.053949,-0.012286,0.000000,0.000000,2.144309
cancer,100.0,-0.651824,1.163949,-5.233560,-0.833133,-0.833133,0.000000,2.747383
capricorn,100.0,1.099097,2.081911,-2.713659,0.000000,0.000000,2.498173,4.778870
gemini,100.0,0.622123,1.826073,-2.881411,-0.003513,0.000000,0.958189,4.971078
leo,100.0,0.194444,1.008418,-3.217282,0.000000,0.000000,0.000000,5.364760
libra,100.0,-0.025011,1.432796,-3.288515,-0.280045,0.000000,0.161156,4.998384
pisces,100.0,0.196069,2.104147,-3.295165,-0.670551,0.000000,1.302250,4.667364
sagittarius,100.0,1.084189,1.997217,-2.771941,0.000000,0.425365,2.040791,10.204202
scorpio,100.0,1.507369,2.231261,-2.853152,0.000000,0.501075,2.803655,5.130027
taurus,100.0,0.124200,2.181325,-3.279559,-0.841871,0.000000,0.900514,5.476754
virgo,100.0,0.419337,1.360263,-3.323164,0.000000,0.000000,1.071917,6.384461
zodiac,100.0,0.166548,1.235362,-4.037970,-0.033718,0.000000,0.721900,4.027055

In [54]:
df_summary.sort_values("mean",ascending=False,inplace=True)
df_summary

,count,mean,std,min,25%,50%,75%,max
scorpio,100.0,1.507369,2.231261,-2.853152,0.000000,0.501075,2.803655,5.130027
capricorn,100.0,1.099097,2.081911,-2.713659,0.000000,0.000000,2.498173,4.778870
sagittarius,100.0,1.084189,1.997217,-2.771941,0.000000,0.425365,2.040791,10.204202
gemini,100.0,0.622123,1.826073,-2.881411,-0.003513,0.000000,0.958189,4.971078
virgo,100.0,0.419337,1.360263,-3.323164,0.000000,0.000000,1.071917,6.384461
aquarius,100.0,0.349854,1.881590,-4.381791,-0.330350,0.000000,1.247935,5.017401
pisces,100.0,0.196069,2.104147,-3.295165,-0.670551,0.000000,1.302250,4.667364
leo,100.0,0.194444,1.008418,-3.217282,0.000000,0.000000,0.000000,5.364760
zodiac,100.0,0.166548,1.235362,-4.037970,-0.033718,0.000000,0.721900,4.027055
taurus,100.0,0.124200,2.181325,-3.279559,-0.841871,0.000000,0.900514,5.476754
libra,100.0,-0.025011,1.432796,-3.288515,-0.280045,0.000000,0.161156,4.998384
aries,100.0,-0.064103,0.946661,-4.053949,-0.012286,0.000000,0.000000,2.144309
cancer,100.0,-0.651824,1.163949,-5.233560,-0.833133,-0.833133,0.000000,2.747383

In [55]:
df_summary.to_csv(os.path.join(path,"data_summary.csv"))